MENU_CLASSES = enumerate(("top", "footer",))

ICON_CLASSES = enumerate(("top", "footer",))

LAYER_CLASSES = (

)


SUBPRODUCT_TYPES = (
    ("power", "Источники питания"),
    ("control", "Контроллеры"),
    ("lenta", "Лента"),
    ("nakladka", "Накладки FOTON"),
    ("profile", "Профиль"),
    ("ramka", "Рамки / накладки"),
    ("lamp", "Светильники"),
    ("chair", "Стулья"),
    ("track", "Треки"),
    (None, "Другое"),
)

PRODUCT_FLAGS = (
    ("draw_first", "draw_first"),
    ("show_trigger", "show_trigger"),
    ("is_vivod", "is_vivod"),
    ("add_to_cart", "add_to_cart"),
    ("custom_params", "custom_params"),
    ("show_category_color", "показывать цвет в карточке продукта"),
    ("is_main_sub", "is_main_sub"),
    ("is_dependent", "is_dependent"),
)


MANAGER_PRICES = (
    (0, "0"),
    (1, "1"),
    (2, "2"),
)


(STAFF, USER, BUYER, DESIGNER, PARTNER) = ("staff", "user", "buyer", "designer", "partner")

USER_TYPES = (
    (USER, "нет роли"),
    (STAFF, "сотрудник"),
    (BUYER, "покупатель"),
    (DESIGNER, "дизайнер"),
    (PARTNER, "партнёр"),
)

TAG_UPLOADS = ([s, s] for s in [
    "2020",
    "3d",
    "400",
    "app",
    "auroom",
    "auroom_black",
    "award",
    "brandvanegmond",
    "dogovor",
    "eurotrack",
    "foscarini",
    "foton_s",
    "foton_t",
    "gypsum_m50",
    "icon_400_400",
    "images",
    "img_magazine",
    "insperations",
    "jane",
    "jpg",
    "light_up_floor",
    "locus",
    "main",
    "main-page",
    "main_page",
    "minimal_new",
    "modular_60",
    "nautilus_new",
    "new_banners",
    "new_system_page",
    "oreo_in_ip",
    "oreo_ip",
    "p.d.f",
    "pdnt",
    "point_10",
    "point_20",
    "post",
    "premy2018",
    "profiles",
    "project",
    "ring_pdnt",
    "shemu",
    "slider_image",
    "storage",
    "svetilnik",
    "svetilniki_inf25",
    "trekovie_svetilniki",
])

TAG_UPLOADS = (
    #  ~ ('shemu', 'media / uploads / svetilnik'),
    #  ~ ('shemu', 'media / uploads / shemu'),
    #  ~ ('pdnt', 'media / uploads / pdnt'),

#  ~ )



    ("big_files", "big_files"),
    ("chat/upload", "upload"),
    ("contacts","contacts"),
    ("feedback/upload", "upload"),
    ("highslide", "highslide"),
    ("highslide/graphics", "graphics"),
    ("images", "images"),
    ("images/error", "error"),
    ("images/new_main", "new_main"),
    ("lightcall", "lightcall"),
    ("lightcall/upload", "upload"),

    ("mediafiles","mediafiles"),
    ("mediafiles/2019", "2019"),
    ("pdf", "pdf"),
    ("uploads", "uploads"),
    ("uploads/2018", "2018"),
    ("uploads/3d", "3d"),
    ("uploads/about", "about"),
    ("uploads/angles", "angles"),
    ("uploads/app", "app"),
    ("uploads/aqua", "aqua"),
    ("uploads/artemide", "artemide"),
    ("uploads/audio", "audio"),
    ("uploads/award", "award"),
    ("uploads/award21", "award21"),
    ("uploads/awards_banners", "awards_banners"),
    ("uploads/backlight", "backlight"),
    ("uploads/blog", "blog"),
    ("uploads/bp", "bp"),
    ("uploads/brandvanegmond", "brandvanegmond"),
    ("uploads/cabinet", "cabinet"),
    ("uploads/casambi", "casambi"),
    ("uploads/cininils", "cininils"),
    ("uploads/common_photos", "common_photos"),
    ("uploads/components", "components"),
    ("uploads/conf", "conf"),
    ("uploads/contacts", "contacts"),
    ("uploads/controllers", "controllers"),
    ("uploads/custom_images", "custom_images"),
    ("uploads/davidegroppi", "davidegroppi"),
    ("uploads/deltalight", "deltalight"),
    ("uploads/documents", "documents"),
    ("uploads/dogovor", "dogovor"),
    ("uploads/email", "email"),
    ("uploads/foscarini", "foscarini"),
    ("uploads/hidden_round", "hidden_round"),
    ("uploads/icon_400_400", "icon_400_400"),
    ("uploads/icons_3d", "icons_3d"),
    ("uploads/icons_for_catalog", "icons_for_catalog"),
    ("uploads/ideas", "ideas"),
    ("uploads/ikon", "ikon"),
    ("uploads/img_magazine", "img_magazine"),
    ("uploads/ingomaurer", "ingomaurer"),
    ("uploads/insperations", "insperations"),
    ("uploads/jane", "jane"),
    ("uploads/kundalini", "kundalini"),
    ("uploads/leadership", "leadership"),
    ("uploads/main", "main"),
    ("uploads/main_page", "main_page"),
    ("uploads/managers", "managers"),
    ("uploads/marset", "marset"),
    ("uploads/martinelliluce", "martinelliluce"),
    ("uploads/menu", "menu"),
    ("uploads/molto_luce", "molto_luce"),
    ("uploads/moooi", "moooi"),
    ("uploads/mosbuild2014foto", "mosbuild2014foto"),
    ("uploads/nemo", "nemo"),
    ("uploads/new_banners", "new_banners"),
    ("uploads/new_lents", "new_lents"),
    ("uploads/news", "news"),
    ("uploads/novue", "novue"),
    ("uploads/other", "other"),
    ("uploads/pallucco", "pallucco"),
    ("uploads/p.d.f", "p.d.f"),
    ("uploads/pdf-compress", "pdf-compress"),
    ("uploads/photometry_pdf", "photometry_pdf"),
    ("uploads/premy2018", "premy2018"),
    ("uploads/premy2018-2", "premy2018-2"),
    ("uploads/profiles", "profiles"),
    ("uploads/project", "project"),
    ("uploads/quasar", "quasar"),
    ("uploads/round", "round"),
    ("uploads/sale", "sale"),
    ("uploads/santacole", "santacole"),
    ("uploads/shemu", "shemu"),
    ("uploads/shops", "shops"),
    ("uploads/sid", "sid"),
    ("uploads/slider_image", "slider_image"),
    ("uploads/storage", "storage"),
    ("uploads/svetilnik", "svetilnik"),
    ("uploads/svetodesign", "svetodesign"),
    ("uploads/svg", "svg"),
    ("uploads/test", "test"),
    ("uploads/test3", "test3"),
    ("uploads/tobias_grau", "tobias_grau"),
    ("uploads/top-banners", "top-banners"),
    ("uploads/transfer_info_doc", "transfer_info_doc"),
    ("uploads/video", "video"),
    ("uploads/video_main", "video_main"),
    ("uploads/vipsvet", "vipsvet"),
    ("uploads/webp", "webp"),
)

TAG_UPLOADS = [[b, a] for a, b in TAG_UPLOADS]
